-- run this code manually on SQL editor on Supabase to create tables
create table mercadolibre_searchs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    query text not null unique
);