-- run this code manually on SQL editor on Supabase to create tables
create table mercadolibre_products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    query text not null,
    title text not null,    
    permalink text not null unique, -- this is the product link from MercadoLivre
    thumbnail text not null,
    price numeric not null
);

/* Adding disable column to track
   product availability status */
ALTER TABLE mercadolibre_products
ADD COLUMN hide boolean DEFAULT false NOT NULL;

/* only used to maintain the system awake on free version of Supabase */
create table internal_data_update (
    id bigint generated by default as identity primary key,
    last_update text not null    
);

insert into internal_data_update (last_update) values (now());
update internal_data_update set last_update = now() where id = 1;

/* Adding alert_submitted column to check
   if an alert was submitted for a product */
ALTER TABLE mercadolibre_products
ADD COLUMN alert_submitted boolean DEFAULT false NOT NULL;

mercadolibre_searchs